version: '3.8'

services:
  java-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-react-network
    depends_on:
      - mysql
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/noteapp?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - spring-boot-react-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

networks:
  spring-boot-react-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  java-spring-data:
    driver: local
