version: '3.8'

services:
  java-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-react-network
    depends_on:
      - mysql
    volumes:
      - java-spring-data:/app/data
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - spring-boot-react-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  spring-boot-react-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  java-spring-data:
    driver: local
